### ISSUE TITLE
No Issue: Thank You for provide amazing theme

### ISSUE THREAD

**Issue by luasenvy** [themefisher/pinwheel-astro#14]
i like this theme. thank you again.

Astro is a really good framework, but I rewrote it because I was familiar with nextjs.

If there's anyone like me, I'd appreciate it if you could use it freely.

link: [nextjs-pinwheel-astro](https://github.com/luasenvy/nextjs-pinwheel-astro)

**Comment by mehedi-sharif** [comment]
Thank you for choosing our design and for taking the initiative to rewrite it in Next.js! We love that you've customized it to fit your needs. We'll be adding this Next.js version to our website so that others can also benefit from your work. Thanks again for contributing to the community! 

Note: @tfsomrat  please take action .
